-- ============================================================
-- Contact page content schema + RLS
-- Public can read active contact cards.
-- Only admins can insert/update/delete contact cards.
--
-- Prerequisite:
-- - public.is_admin() exists and is SECURITY DEFINER.
--   If needed, run docs/supabase_admin_auth_fix.sql first.
--
-- Safe to run multiple times.
-- ============================================================

create table if not exists public.contact_cards (
  id bigint generated by default as identity primary key,
  label text not null,
  value text not null,
  contact_type text not null default 'email',
  cta_label text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contact_cards_contact_type_check
    check (contact_type in ('email', 'url', 'phone', 'text'))
);

create index if not exists contact_cards_order_idx
  on public.contact_cards (display_order, id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_contact_cards_updated_at on public.contact_cards;
create trigger trg_contact_cards_updated_at
before update on public.contact_cards
for each row
execute function public.set_updated_at();

insert into public.contact_cards (label, value, contact_type, cta_label, display_order, is_active)
select *
from (
  values
    ('Club President', 'madisonrugbypresident@gmail.com', 'email', null, 1, true),
    ('Head Coach Mark Fowler', 'Fowlerma@alumni.vcu.edu', 'email', null, 2, true),
    ('Instagram', 'https://www.instagram.com/jmumensrugby/', 'url', 'Visit @jmumensrugby', 3, true)
) as seed(label, value, contact_type, cta_label, display_order, is_active)
where not exists (select 1 from public.contact_cards);

alter table public.contact_cards enable row level security;

drop policy if exists "Public read active contact cards" on public.contact_cards;
create policy "Public read active contact cards"
on public.contact_cards
for select
to anon, authenticated
using (is_active = true or public.is_admin());

drop policy if exists "Admins insert contact cards" on public.contact_cards;
create policy "Admins insert contact cards"
on public.contact_cards
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins update contact cards" on public.contact_cards;
create policy "Admins update contact cards"
on public.contact_cards
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins delete contact cards" on public.contact_cards;
create policy "Admins delete contact cards"
on public.contact_cards
for delete
to authenticated
using (public.is_admin());
