-- ============================================================
-- Donate page content schema + RLS
-- Public can read donate settings.
-- Only admins can insert/update/delete donate settings.
--
-- Prerequisite:
-- - public.is_admin() exists and is SECURITY DEFINER.
--   If needed, run docs/supabase_admin_auth_fix.sql first.
--
-- Safe to run multiple times.
-- ============================================================

create table if not exists public.donate_content_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_donate_content_settings_updated_at on public.donate_content_settings;
create trigger trg_donate_content_settings_updated_at
before update on public.donate_content_settings
for each row
execute function public.set_updated_at();

insert into public.donate_content_settings (key, value, description)
values
  ('venmo_url', 'https://venmo.com/u/David-Neal-84', 'Venmo URL used for the Donate page CTA and QR code.'),
  ('venmo_recipient_name', 'David Neal', 'Recipient name used in Donate page copy and QR alt text.')
on conflict (key) do update
set value = excluded.value,
    description = excluded.description,
    updated_at = now();

alter table public.donate_content_settings enable row level security;

drop policy if exists "Public read donate_content_settings" on public.donate_content_settings;
create policy "Public read donate_content_settings"
on public.donate_content_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Admins insert donate_content_settings" on public.donate_content_settings;
create policy "Admins insert donate_content_settings"
on public.donate_content_settings
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins update donate_content_settings" on public.donate_content_settings;
create policy "Admins update donate_content_settings"
on public.donate_content_settings
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins delete donate_content_settings" on public.donate_content_settings;
create policy "Admins delete donate_content_settings"
on public.donate_content_settings
for delete
to authenticated
using (public.is_admin());
