-- S-06: Data-free baseline of the live Supabase schema.
--
-- This migration intentionally contains schema and configuration only. It does
-- not copy production users, administrator IDs, roster entries, media records,
-- or other site content.
--
-- The baseline is timestamped before the first tracked remediation migration so
-- a clean database can replay the complete migration chain in order.

create table public.admins (
  user_id uuid not null,
  created_at timestamptz not null default now(),
  constraint admins_pkey primary key (user_id),
  constraint admins_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade
);

create table public.coaches (
  id bigint not null,
  name text,
  position text,
  bio text,
  headshot_url text,
  constraint coaches_pkey primary key (id)
);

comment on table public.coaches is 'Coach information';

create table public.contact_cards (
  id bigint generated by default as identity,
  label text not null,
  value text not null,
  contact_type text not null default 'email',
  cta_label text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contact_cards_pkey primary key (id),
  constraint contact_cards_contact_type_check
    check (contact_type = any (array['email'::text, 'url'::text, 'phone'::text, 'text'::text]))
);

create table public.donate_content_settings (
  id bigint generated by default as identity,
  key text not null,
  value text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint donate_content_settings_pkey primary key (id),
  constraint donate_content_settings_key_key unique (key)
);

create table public.join_content_faq (
  id uuid not null default gen_random_uuid(),
  question text not null,
  answer text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint join_content_faq_pkey primary key (id),
  constraint join_content_faq_question_unique unique (question)
);

create table public.join_content_schedule (
  id uuid not null default gen_random_uuid(),
  label text not null,
  detail text not null,
  display_order integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint join_content_schedule_pkey primary key (id),
  constraint join_content_schedule_label_unique unique (label)
);

create table public.join_content_settings (
  id uuid not null default gen_random_uuid(),
  key text not null,
  value text not null,
  description text,
  updated_at timestamptz not null default now(),
  constraint join_content_settings_pkey primary key (id),
  constraint join_content_settings_key_key unique (key)
);

create table public.matches (
  id bigint not null,
  season_id text,
  season_name text,
  date date,
  opponent text,
  side text,
  home boolean,
  result text,
  show_result boolean,
  notes text,
  constraint matches_pkey primary key (id)
);

comment on table public.matches is 'Description of matches on the schedule.';

create table public.media (
  id bigint generated by default as identity,
  album text not null,
  file_path text not null,
  featured boolean not null default false,
  upload_date timestamptz default now(),
  season_id text,
  home_carousel boolean not null default false,
  join_page boolean not null default false,
  constraint media_pkey primary key (id)
);

create table public.roster (
  id bigint not null,
  name text,
  position text,
  year text,
  major text,
  hometown text,
  height text,
  weight smallint,
  bio text,
  headshot_url text,
  constraint roster_pkey primary key (id)
);

comment on table public.roster is 'Roster information';

create table public.sponsors (
  id uuid not null default gen_random_uuid(),
  name text not null,
  website_url text,
  logo_url text,
  logo_object_path text,
  alt_text text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint sponsors_pkey primary key (id)
);

create index contact_cards_order_idx
  on public.contact_cards (display_order, id);

create index join_content_faq_order_idx
  on public.join_content_faq (display_order);

create index join_content_schedule_order_idx
  on public.join_content_schedule (display_order);

create index media_home_carousel_true_idx
  on public.media (id)
  where home_carousel = true;

create index media_join_page_true_idx
  on public.media (id)
  where join_page = true;

create index sponsors_order_idx
  on public.sponsors (display_order);

create function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins as a
    where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated, service_role;

create function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

grant execute on function public.set_updated_at()
  to public, anon, authenticated, service_role;

create trigger trg_contact_cards_updated_at
before update on public.contact_cards
for each row execute function public.set_updated_at();

create trigger trg_donate_content_settings_updated_at
before update on public.donate_content_settings
for each row execute function public.set_updated_at();

create trigger trg_join_content_faq_updated_at
before update on public.join_content_faq
for each row execute function public.set_updated_at();

create trigger trg_join_content_schedule_updated_at
before update on public.join_content_schedule
for each row execute function public.set_updated_at();

create trigger trg_join_content_settings_updated_at
before update on public.join_content_settings
for each row execute function public.set_updated_at();

create trigger trg_sponsors_updated_at
before update on public.sponsors
for each row execute function public.set_updated_at();

alter table public.admins enable row level security;
alter table public.coaches enable row level security;
alter table public.contact_cards enable row level security;
alter table public.donate_content_settings enable row level security;
alter table public.join_content_faq enable row level security;
alter table public.join_content_schedule enable row level security;
alter table public.join_content_settings enable row level security;
alter table public.matches enable row level security;
alter table public.media enable row level security;
alter table public.roster enable row level security;
alter table public.sponsors enable row level security;

create policy "Admins can manage admins"
on public.admins
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can read admins"
on public.admins
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "Admin delete coaches"
on public.coaches
for delete to authenticated
using (public.is_admin());

create policy "Admin insert coaches"
on public.coaches
for insert to authenticated
with check (public.is_admin());

create policy "Admin update coaches"
on public.coaches
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins delete coaches"
on public.coaches
for delete to authenticated
using (public.is_admin());

create policy "Admins insert coaches"
on public.coaches
for insert to authenticated
with check (public.is_admin());

create policy "Admins update coaches"
on public.coaches
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Enable read access for all users"
on public.coaches
for select to public
using (true);

create policy "Public read coaches"
on public.coaches
for select to anon, authenticated
using (true);

create policy "Admins delete contact cards"
on public.contact_cards
for delete to authenticated
using (public.is_admin());

create policy "Admins insert contact cards"
on public.contact_cards
for insert to authenticated
with check (public.is_admin());

create policy "Admins update contact cards"
on public.contact_cards
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read active contact cards"
on public.contact_cards
for select to anon, authenticated
using (is_active = true or public.is_admin());

create policy "Admins delete donate_content_settings"
on public.donate_content_settings
for delete to authenticated
using (public.is_admin());

create policy "Admins insert donate_content_settings"
on public.donate_content_settings
for insert to authenticated
with check (public.is_admin());

create policy "Admins update donate_content_settings"
on public.donate_content_settings
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read donate_content_settings"
on public.donate_content_settings
for select to anon, authenticated
using (true);

create policy "Admins delete join_content_faq"
on public.join_content_faq
for delete to authenticated
using (public.is_admin());

create policy "Admins insert join_content_faq"
on public.join_content_faq
for insert to authenticated
with check (public.is_admin());

create policy "Admins update join_content_faq"
on public.join_content_faq
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read active join_content_faq"
on public.join_content_faq
for select to anon, authenticated
using (is_active = true or public.is_admin());

create policy "Admin delete join_content_schedule"
on public.join_content_schedule
for delete to authenticated
using (public.is_admin());

create policy "Admin manage join_content_schedule"
on public.join_content_schedule
for insert to authenticated
with check (public.is_admin());

create policy "Admin update join_content_schedule"
on public.join_content_schedule
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read join_content_schedule"
on public.join_content_schedule
for select to public
using (true);

create policy "Admin delete join_content_settings"
on public.join_content_settings
for delete to authenticated
using (public.is_admin());

create policy "Admin manage join_content_settings"
on public.join_content_settings
for insert to authenticated
with check (public.is_admin());

create policy "Admin update join_content_settings"
on public.join_content_settings
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read join_content_settings"
on public.join_content_settings
for select to public
using (true);

create policy "Admin delete matches"
on public.matches
for delete to authenticated
using (public.is_admin());

create policy "Admin insert matches"
on public.matches
for insert to authenticated
with check (public.is_admin());

create policy "Admin update matches"
on public.matches
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins delete matches"
on public.matches
for delete to authenticated
using (public.is_admin());

create policy "Admins insert matches"
on public.matches
for insert to authenticated
with check (public.is_admin());

create policy "Admins update matches"
on public.matches
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Enable read access for all users"
on public.matches
for select to public
using (true);

create policy "Public read matches"
on public.matches
for select to anon, authenticated
using (true);

create policy "Admins delete media"
on public.media
for delete to authenticated
using (public.is_admin());

create policy "Admins insert media"
on public.media
for insert to authenticated
with check (public.is_admin());

create policy "Admins update media"
on public.media
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read media"
on public.media
for select to anon, authenticated
using (true);

create policy "Admin delete roster"
on public.roster
for delete to authenticated
using (public.is_admin());

create policy "Admin insert roster"
on public.roster
for insert to authenticated
with check (public.is_admin());

create policy "Admin update roster"
on public.roster
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins delete roster"
on public.roster
for delete to authenticated
using (public.is_admin());

create policy "Admins insert roster"
on public.roster
for insert to authenticated
with check (public.is_admin());

create policy "Admins update roster"
on public.roster
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Enable read access for all users"
on public.roster
for select to public
using (true);

create policy "Public read roster"
on public.roster
for select to anon, authenticated
using (true);

create policy "Admins delete sponsors"
on public.sponsors
for delete to authenticated
using (public.is_admin());

create policy "Admins insert sponsors"
on public.sponsors
for insert to authenticated
with check (public.is_admin());

create policy "Admins update sponsors"
on public.sponsors
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public read active sponsors"
on public.sponsors
for select to anon, authenticated
using (is_active = true or public.is_admin());

-- The bucket row is deployment configuration rather than website content.
-- ON CONFLICT keeps local resets compatible with config.toml bucket creation.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'rugby-media',
  'rugby-media',
  true,
  null,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Admins delete rugby-media headshots objects"
on storage.objects
for delete to authenticated
using (
  bucket_id = 'rugby-media'
  and name like 'headshots/%'
  and public.is_admin()
);

create policy "Admins delete rugby-media objects"
on storage.objects
for delete to authenticated
using (bucket_id = 'rugby-media' and public.is_admin());

create policy "Admins delete rugby-media sponsors objects"
on storage.objects
for delete to authenticated
using (
  bucket_id = 'rugby-media'
  and name like 'sponsors/%'
  and public.is_admin()
);

create policy "Admins insert rugby-media headshots objects"
on storage.objects
for insert to authenticated
with check (
  bucket_id = 'rugby-media'
  and name like 'headshots/%'
  and public.is_admin()
);

create policy "Admins insert rugby-media objects"
on storage.objects
for insert to authenticated
with check (bucket_id = 'rugby-media' and public.is_admin());

create policy "Admins insert rugby-media sponsors objects"
on storage.objects
for insert to authenticated
with check (
  bucket_id = 'rugby-media'
  and name like 'sponsors/%'
  and public.is_admin()
);

create policy "Admins update rugby-media headshots objects"
on storage.objects
for update to authenticated
using (
  bucket_id = 'rugby-media'
  and name like 'headshots/%'
  and public.is_admin()
)
with check (
  bucket_id = 'rugby-media'
  and name like 'headshots/%'
  and public.is_admin()
);

create policy "Admins update rugby-media objects"
on storage.objects
for update to authenticated
using (bucket_id = 'rugby-media' and public.is_admin())
with check (bucket_id = 'rugby-media' and public.is_admin());

create policy "Admins update rugby-media sponsors objects"
on storage.objects
for update to authenticated
using (
  bucket_id = 'rugby-media'
  and name like 'sponsors/%'
  and public.is_admin()
)
with check (
  bucket_id = 'rugby-media'
  and name like 'sponsors/%'
  and public.is_admin()
);

create policy "Public read rugby-media headshots objects"
on storage.objects
for select to anon, authenticated
using (bucket_id = 'rugby-media' and name like 'headshots/%');

create policy "Public read rugby-media objects"
on storage.objects
for select to anon, authenticated
using (bucket_id = 'rugby-media');

create policy "Public read rugby-media sponsors objects"
on storage.objects
for select to anon, authenticated
using (bucket_id = 'rugby-media' and name like 'sponsors/%');

grant usage on schema public to anon, authenticated, service_role;
grant all privileges on all tables in schema public
  to anon, authenticated, service_role;
grant all privileges on all sequences in schema public
  to anon, authenticated, service_role;
